### ISSUE TITLE
Refactoring Meta-issue

### ISSUE THREAD

**Issue by dereklhansen** [prob-ml/bliss#383]
In trying to implement the Predict module (#380), I've come across a few things that are confusing when interfacing with the bliss code base. While the program itself works fine, this could make it harder to onboard new students and convince outside collaborators to use the code base.

Rather than a giant refactoring PR, we can collect a list of atomic changes that can be made, and keep them each as separate issues. The scope of these changes should be limited to refactoring. Functionality cannot be added, but it can (and should) be removed if we don't need it anymore. Anything listed without an issue attached might need further clarification or discussion.

Before listing the issues, it is helpful to clarify at a high-level what the codebase currently does:
- Inference: Given an astronomical object, return variational parameters (locations, fluxes, star/galaxy classification, and galaxy parameters)
- Training: Use simulated data to train the models for inference
- Data: Facilitate downloading and processing images and catalog info (e.g. the estimated PSF) from different surveys (currently just SDSS?)
- Simulation: Wrap the Galsim library for simulating realistic gax
- Visualization: Plot astronomical images and the inferred catalog. 

## General
- [x] Reorganize hydra configs and reduce duplication (#372)
- [x] #385 

## Unused functionality
- [x] Remove tuning code from main repo ("tune.py") (and delete tests) (#407)
- [x] Remove FNP from main repo ("models/fnp.py") (and delete tests) (#414)
- [x] Remove "bliss/optimizer.py" (and just create `Adam` instances directly where they are needed) (#404)

## Inference
- [x] Add docstrings to specify the keys in output dictionaries (ImageEncoder, BinaryEncoder, GalaxyEncoder, etc...)
- [x] Public methods for ImageEncoder should be more clear 
- [x] Names should be more specific for Galaxy Autoencoder objects (#376).
- [x] #341

## Data 
- [x] The SloanDigitalSkySurvey class does too much (#381)

## Simulation
- [x] Remove noise_factor from Galsim galaxies (#373)

## Visualization
- [ ] Separate top level plotting code from reporting.py (separate issue)

**Comment by dereklhansen** [comment]
Going to close this since we did pretty much everything other than refactor `reporting.py`.
