### ISSUE TITLE
Roadmap: PSF Homogenization feature

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#633]
Roadmap for issue #378. This is intended to layout a set of concrete tasks/issues for @wangchv to work on. @jeff-regier let me know if you would add anything or have any suggestions. 

## Simulated 
- [x] create a full image decoder that only uses galsim
- [x] create a PsfSampler class that returns a random sample of psfs from a file or galsim
    - ~~Create functions like `.from_file`, `.from_array` and a subclass that uses galsim with varying FWHM~~
- [x] extend full image decoder to output PSF homogenized images using functions in `homogenization.py`
- [ ] train `detection_encoder` on homogenized dataset that uses a random galsim PSF, check results are reasonable
- [ ] compare performance between encoders trained on homogenized images vs not (precision, recall, etc.)

## SDSS Data
- [ ] Reimplement `psf_at_points` in `sdss.py`. See this [diff](https://github.com/prob-ml/bliss/commit/02bf153dd87aa6eedf18eacbc0fcce274c2f9b16). 
- [ ] Decide on a set of frame/camcols/runs to use in SDSS that overlap with DeCals ?
    - Might need to close or make progress in #623
- [ ] Use `psf_at_points` to create a sample dataset of PSFs across previously decided frame/camcols/runs/position
- [ ] train encoders on homogenized dataset using random sample of these real PSFs
    - the psfs extracted in the previous tasks should be used as input to `PsfSampler` class 
- [ ] evaluate performance of encoders trained on real PSF homogenized dataset across multiple frames vs one trained on a single PSF

## If time
- [ ] Train and evaluate `binary_encoder` and `galaxy_encoder` as well

**Comment by jeff-regier** [comment]
Great!

**Comment by jeff-regier** [comment]
It's been difficult to homogenize the images adequately -- let's try encoding the PSF instead (#694)
