### ISSUE TITLE
Roadmap: Coadd Feature

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#635]
This issue is intended as a roadmap with concrete tasks to work on for @wangmallory. 

## Stage 0: Dither only
For this milestone, let's only implement dither. We keep background and PSF fixed, but noise can be different between exposures. 

- Single Galsim galaxies
    - [x] Understand how Galsim WCS can handle differences in offset
    - [x] Use `torch.grid_sample` to align single exposures (uncentered images) with interpolation. Ideally using the output from a WCS
        -  From galsim WCS or an astropy WCS in the case that the former does not handle multiple points at once?
        - to align images, after grid_sample, need to crop a region around all images corresponding to max_shfit.
    - [x] check that interpolated images make sense (use a very small image to look at individual pixel values)

- Simulate Coadds with Decoder
    - [x] implement full image decoder using only galsim (ismael) 
    - [x] extend the full image decoder (ideally with inheritance) to output coadded images 
        - [x] create a (astropy) WCS for each separate image drawn and a "global" WCS (centered image)
        - [x] combine each image WCS, global WCS, and grid centered at each pixel of uncentered images to create a transformed grid
        - [x] ingest new grid in `torch.grid_sample` to align images
        - [x] crop region outside the images depending on max shift
        - [x] ensure each single exposure has same background, PSF, but different noise realization
        - [x] combine images with direct coadd equation (uses weights = 1/SNR)

- [x] Train and test location encoder on images from this "coadd decoder", compare with an encoder trained on non-coadd images.
    - **Note:** Ideally, should be trivial to plug-in this decoder if we sub-class it from the Full Image Decoder (which Ismael needs to train/evaluate on anyways)

### Key Figures 
- Dim stars (single-exposure) becoming brighter when coadded many single exposures 
- Schematic showing alignment + coadding procedure
- Money plot : show detection (precisoin, recall, f1 score) as a function of magnitude being higher on coadded images

## Stage 1: Rotations
- [ ] Understand how rotations are implemented in `descwl-shear-sims`, what functionality should we borrow? Could we get away with just implementating rotations via the WCS ? 

## Stage 2: More Realism
- [ ] Explore other ways of doing coadds?
- [ ] Borrow even more functionality from `descwl-shear-sims`, like bleed_trails, cosmic rays, brighter-fatter, etc.? Probably out of the scope of this project though

## Resources
- Shear sims and simulating coadds code: https://github.com/aguinot/descwl-shear-sims
- [papers](https://docs.google.com/document/d/1NQk1Wt0zhwqyZovuQkPsBo7gpd3UogdZZ0DUfrDzjT8/edit)

**Comment by jeff-regier** [comment]
Manuscript submitted!
